{{- if and (eq .Values.deploymentMethod "llmd") (eq .Values.llmd.flowControl true) }}
{{- range .Values.serviceAccounts }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb-{{ .name }}-{{ .namespace }}-llmviewer
subjects:
  - kind: ServiceAccount
    name: {{ .name }}
    namespace: {{ .namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: llm-viewer
{{- end }}
{{- end }}
