{{- if and (eq .Values.deploymentMethod "llmd") (eq .Values.llmd.flowControl true) }}
{{- range .Values.serviceAccounts }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    app: llmd-demo
{{- end }}
{{- end }}
